- .travis.yml
- .travis/build.sh
- .travis/install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/batfish/pybatfish/1)
> Add travis configuration

- docs/source/quickstart.rst
* Remove propertySpec filter (so the result shown in the doc is matches up with reality)
* Add notebook link
> Update quickstart doc

- pybatfish/client/workhelper.py
- pybatfish/datamodel/answer/table.py
- tests/client/test_workhelper.py
* Update github issue link
* Delete unused stale-work-check and related test
> Update issue link

- jupyter_notebooks/Getting started with Batfish.ipynb
- jupyter_notebooks/startup.py
Add notebook startup file.
Can be invoked from a notebook in the notebooks dir with:
```
% load startup.py
```
> Add notebook startup file

- pybatfish/question/question.py
Add support for adding exclusions for `batfish` questions.
> Support exclusions

- pybatfish/client/commands.py
- pybatfish/client/restv2helper.py
- requirements.txt
- setup.py
turns out that requests defaults to simplejson if the library is available, so i just had to add it as a dependency. 
other changes are automatic refactoring of imports by pycharm
> add simplejson

- pybatfish/question/question.py
> question: add validation for nodeSpec/nodePropertySpec

- .travis/build.sh
- jupyter_notebooks/startup.py
- setup.cfg
F403 'from pybatfish.client.commands import *' used; unable to detect undefined names
F405 'bf_logger' may be undefined, or defined from star imports: pybatfish.client.commands
> startup: use import * from client commands

- pybatfish/client/commands.py
- tests/integration/test_network_funcs.py
Instead of a weird unreadable dict.
> bf_list_networks() now returns a list of names

- pybatfish/question/question.py
- also  moved `long` validation to correct place
> Interface spec validation

- .gitignore
> Add jupyter checkpoints to gitignore

- .gitignore
- pybatfish/question/question.py
- tests/util/test_question.py
• Filter module members using class name QuestionMeta instead of isfunction (which returned no results)
• Add test_list_questions() to make sure list_questions() doesn't return an empty list when there are actually questions available
> Fix bug in list_questions()

- .idea/codeStyles/codeStyleConfig.xml
- pybatfish/datamodel/answer/base.py
- tests/datamodel/answer/test_base.py
- tests/datamodel/answer/test_tableanswerelement.py
also moved tests to a new file to mirror code structure
> Schema selfdescribingobject

- jupyter_notebooks/Getting started with Batfish.ipynb
- jupyter_notebooks/Test and Validation.ipynb
- tests/integration/test_notebook.py
Related fixes:
- execute the notebook in the directory it is in
- overwrite in test/validation notebook
- Fix path to example network
> Test all Jupyter notebooks

- jupyter_notebooks/Getting started with Batfish.ipynb
- tests/integration/test_notebook.py
will merge in the changes from master after batfish/pybatfish#32 is merged
> Testing execution counts of saved notebooks

- .travis/install.sh
- jupyter_notebooks/Getting started with Batfish.ipynb
Fix z3 install link in `.travis/install.sh`
> Update z3 install link

- jupyter_notebooks/Getting started with Batfish.ipynb
- jupyter_notebooks/startup.py
- pybatfish/datamodel/answer/base.py
- pybatfish/datamodel/flowtrace.py
- pybatfish/datamodel/flowtracehop.py
- tests/datamodel/test_flowtracehop.py
the traceroute output is still not where i'd like it to be but its a step forward
> prettify traceroute output a bit and use in getting started

- jupyter_notebooks/ACL debugging.ipynb
- jupyter_notebooks/Getting started with Batfish.ipynb
- jupyter_notebooks/Introduction to Route Analysis.ipynb
- jupyter_notebooks/Validating Configuration Settings.ipynb
Update example network references to point to `Pybatfish` in notebooks.
> Update notebook example references

- .travis/build.sh
- pybatfish/datamodel/flow.py
- tests/integration/test_notebook.py
Flake wasn't run properly with travis, so fix that and update necessary files.
> Fix flake on travis

- docs/source/questions-generated.rstgen
- pybatfish/question/question.py
- tests/question/test_question.py
- Delete differential parameter from question constructor
- Update signatures for the question metaclass:
- snake_case
- Put common params (question_name, exclusions) at the end
- Update question docs
- Tiny style tweaks to question tests
Needs #70 to pass travis.
> Delete differential parameter from question constructor

- pybatfish/datamodel/primitives.py
- tests/datamodel/test_datamodel_element.py
* Fix return value of as_dict
* Make interface inherit from DataModelElement
> Fix datamodel serialization bugs

- docs/source/datamodel.rst
- jupyter_notebooks/Getting started with Batfish.ipynb
- pybatfish/client/commands.py
- pybatfish/client/session.py
- pybatfish/datamodel/answer/__init__.py
- pybatfish/datamodel/answer/base.py
- pybatfish/datamodel/answer/table.py
- pybatfish/question/question.py
- tests/datamodel/answer/test_tableanswerelement.py
* Rename table answer element -> table answer
* Delete useless functions from QuestionBase, especially help()
* Document Session
* Update notebook
> Update questions, answers and their docs

- pybatfish/client/commands.py
- pybatfish/settings/issues.py
A bit of a hotfix, will add integration tests later.
> Fix datamodel constructors in commands.py

- docs/source/questions-generated.rstgen
- pybatfish/question/question.py
- tests/question/test_question.py
- Update question docs to include new/updated batfish templates
- Tweak allowed values bullet list so `sphinx` doesn't complain
> Update template docs, fix up allowed values formatting

- jupyter_notebooks/ACL debugging.ipynb
- pybatfish/question/question.py
After batfish/batfish#2290 and batfish/batfish#2298
> Update Acl notebook

- .idea/codeStyles/Project.xml
- pybatfish/client/asserts.py
- pybatfish/client/commands.py
- pybatfish/client/session.py
- pybatfish/client/workhelper.py
- pybatfish/client/workitem.py
- pybatfish/question/question.py
- pybatfish/util.py
- setup.cfg
- setup.py
- tests/client/test_workhelper.py
- tests/datamodel/answer/test_tableanswerelement.py
- tests/datamodel/test_acltrace.py
- tests/datamodel/test_filelines.py
- tests/datamodel/test_flowtracehop.py
- tests/datamodel/test_issue.py
- tests/datamodel/test_referencelibrary.py
- tests/datamodel/test_traceevent.py
- tests/integration/test_notebook.py
- tests/settings/test_issues.py
Optimize imports again and actually enforce the order with flake8-import-order
> Enforce import order

- jupyter_notebooks/Getting started with Batfish.ipynb
Added a link to the video in the notebook (and a link to the notebook in the video description)
> Cross link video

- README.md
Add Docker repo and image pointers to readme
> Add Docker repo and image pointers to readme

- jupyter_notebooks/README.md
Provides a quick overview for each.
> README.md for notebooks

- pybatfish/datamodel/flow.py
Interface for specifying path constraints, introduced in batfish/batfish#2356
> Add path constraint parameter class

- pybatfish/datamodel/answer/base.py
- tests/datamodel/answer/test_base.py
- Simplify logic
- Write tests
> Test schema detection in answer deserialization

- jupyter_notebooks/README.md
Also made the Slack link more prominent
> Add Batfish channel link.

- README.md
Clarify getting started section of readme
> Clarify getting started section of readme

- pybatfish/client/consts.py
- pybatfish/client/restv2helper.py
Copy CoordConstsV2 from `Batfish` and apply in REST helper
Also migrate to using `/networks/` instead of deprecated `/containers/` path for v2 calls
> Add CoordConstsV2

- pybatfish/datamodel/primitives.py
- tests/datamodel/test_datamodel_element.py
Quick fix to make `Edge` match `Batfish` serialization (`str`ings instead of `Interface`s)
> Update Edge to match Batfish serialization

- jupyter_notebooks/README.md
Following the existing pattern to add the Analyzing ACLs and Firewall Rules video
> add video to README

- jupyter_notebooks/Analyzing ACLs and Firewall Rules.ipynb
> add youtube link

- pybatfish/client/commands.py
- pybatfish/client/consts.py
- pybatfish/client/restv2helper.py
- tests/integration/roles_snapshot/configs/h1.cfg
- tests/integration/roles_snapshot/configs/h2.cfg
- tests/integration/roles_snapshot/configs/r1.cfg
- tests/integration/roles_snapshot/configs/r2.cfg
- tests/integration/test_network_funcs.py
- tests/integration/test_snapshot_funcs.py
- comport with batfish/batfish#2435
> update node roles API due to upstream changes

- pybatfish/datamodel/flow.py
If ingressInterface is set, ingressVrf is likely None. Don't print that.
> Flow: also don't print None

- pybatfish/client/commands.py
- pybatfish/client/consts.py
- pybatfish/client/restv2helper.py
- tests/integration/test_snapshot_funcs.py
- use new API call from batfish/batfish#2488
- generalize restv2helper functions
> use v2 list_snapshots from upstream

- pybatfish/datamodel/flow.py
- tests/datamodel/test_flow.py
- tests/integration/test_answer_funcs.py
- also now correctly treating `inputInterface` and `outputInterface` as a `NodeInterfacePair`
> More info in str and repr_html for a Hop

- pybatfish/datamodel/flow.py
- tests/datamodel/test_flow.py
- make it consistent with html representation
> Clean up Hop str function

- pybatfish/datamodel/primitives.py
- tests/datamodel/answer/test_tableanswerelement.py
- tests/datamodel/test_primitives.py
- Moves us towards more immutable answer frames
- Should fix some pandas issues where `ListWrapper` is un-hashable
> Switch from lists to FrozenLists in answers

- jupyter_notebooks/Introduction to Forwarding Analysis.ipynb
> Add forwarding analysis notebook

- pybatfish/client/commands.py
- pybatfish/datamodel/primitives.py
- pybatfish/question/question.py
- tests/question/test_question.py
bf_create_check is completely broken.
* Remove and also delete associated functions
* Add a stop-gap measure to make a question into a check in `QuestionBase` itself.
> Remove broken bf_create_check, add stop-gap fix

- pybatfish/datamodel/flow.py
- tests/datamodel/test_flow.py
> only render ports for ipProtocols that have ports

- pybatfish/client/commands.py
I'm also in parallel fixing the backend to reject malformed analyses
> bf_init_analysis: rewrite and fix name

- README.md
update readme to reference batfish readme
> First pass update

- docs/source/questions-generated.rstgen
- jupyter_notebooks/Analyzing ACLs and Firewall Rules.ipynb
- jupyter_notebooks/Provably Safe ACL and Firewall Changes.ipynb
Fix up after batfish/batfish#2661 and other changes.
> Update searchFilters/testFilters/question docs

- jupyter_notebooks/Introduction to Forwarding Change Validation.ipynb
- jupyter_notebooks/README.md
add link to notebook
add link to README
fix configs link
> add link to Intro to Forwarding Change Validation video

- jupyter_notebooks/README.md
Add failure analysis to README
> Add failure analysis to README

- pybatfish/client/diagnostics.py
Specify ACL in PUT header for upload diagnostics (to give permissions to bucket owner).
> Update upload diagnostics

- pybatfish/datamodel/flow.py
- tests/datamodel/test_flow.py
Handle the PreSourceNatOutgoingFilter step in traceroute.
> Show the PreSourceNatOutgoingFilter step in traceroute.

- pybatfish/client/diagnostics.py
- tests/integration/test_diagnostics.py
- tests/integration/test_snapshot_funcs.py
* Split diagnostic integration test into its own file
* Add resource prefix for segregating testing data
> Upload diagnostics testing

- pybatfish/question/question.py
- tests/question/test_question.py
Reject positional arguments in question constructors.
Fixes #222
> Force keyword arguments in question constructor

- jupyter_notebooks/Analyzing the Impact of Failures.ipynb
fix some typos in the notebook
> fix some typos in the notebook

- pybatfish/client/restv2helper.py
- tests/integration/test_answer_funcs.py
* Add test for failing question
* Fix `get_work_log` to work w/ Python 2.7
> Test question failure

- README.md
These instructions mirror what is listed in the Batfish README
> Adding Pybatfish install instructions to the README

- pybatfish/datamodel/primitives.py
- pybatfish/question/question.py
- tests/conftest.py
To be merged after https://github.com/batfish/batfish/pull/3154
> New variable types

- jupyter_notebooks/Analyzing ACLs and Firewall Rules.ipynb
- jupyter_notebooks/networks/example-filters/current/configs/firewall.cfg
Due to some missing policies, searchfilters was trivially passing.
Now passing non-trivially (verified manually)
Fixes #287
> Update configs for Firewall notebook

- pybatfish/datamodel/flow.py
src/dst port, TCP flags, and ICMP codes are not required for all IP packets
> Flow: tolerate missing optional fields

- tests/datamodel/test_flow.py
Separated out from another PR where I had to touch this file.
> test_flow: typo fixes

- docs/source/questions-generated.rstgen
Includes new lpmRoutes question
> Update question docs

- pybatfish/client/options.py
- pybatfish/client/resthelper.py
- pybatfish/client/restv2helper.py
* delete unused variables
* add documentation of the computation and tweak numbers
* retry on read errors
> requests: tweak backoff

- pybatfish/datamodel/primitives.py
- pybatfish/question/question.py
- tests/conftest.py
After https://github.com/batfish/batfish/pull/3428
> new variable type: application spec

- jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb
- jupyter_notebooks/startup.py
In addition to just handling DataFrames
> Handle TableAnswer in notebook's show()

- pybatfish/client/restv2helper.py
* Inline `list_snapshots` params
* Fix error message
> Cleanup list_snapshots REST helper

- jupyter_notebooks/startup.py
- pybatfish/client/commands.py
- pybatfish/client/diagnostics.py
- pybatfish/client/session.py
- pybatfish/client/workhelper.py
- pybatfish/question/question.py
* Get rid of `bf_logger` and `Session.logger` references
* Use logger with name matching module's `__name__` instead
* Use `warning` instead of deprecated `warn` function
> Remove bf_logger

- pybatfish/client/diagnostics.py
- pybatfish/client/internal.py
- pybatfish/client/resthelper.py
- pybatfish/client/restv2helper.py
- pybatfish/client/workhelper.py
- pybatfish/client/workitem.py
- pybatfish/question/question.py
Revamp type hinting imports for Session, to avoid import cycles ([see here](https://mypy.readthedocs.io/en/latest/common_issues.html#import-cycles))
> Revamp Session imports

- pybatfish/client/session.py
Fix get_snapshot error message to be more accurate and helpful.
> Update get_snapshot error message

- pybatfish/client/commands.py
- pybatfish/client/session.py
- pybatfish/client/workhelper.py
Remove `bf_list_questions` and its replacement `Session.list_asked_questions`.
The behavior of these functions isn't intuitive (hides questions asked in Pybatfish when no name is supplied), and the output is not useful for users.
> Remove bf_list_questions

- pybatfish/client/session.py
* Reworded some docstrings
* Added a few missing docstrings
> Cleanup Session docstrings and typing - part 1

- docs/source/questions-generated.rstgen
Include experimental `testRoutePolicies` question in question docs
> Question docs update

- pybatfish/datamodel/flow.py
- tests/datamodel/test_flow.py
> HeaderConstraints: accept single or list of MatchTcpFlags

- tests/client/test_workhelper.py
- tests/question/test_question.py
Stop passing in old stuff (logger) to session constructor
> Update Session constructors

- tests/client/test_questions.py
Test that questions are loaded correctly from (mock) remote service endpoint
> Add test for remote question loading

- docs/source/questions-generated.rstgen
I wanted to update the doc for `bidirectionalTraceroute` but a couple of other changes are along for the ride.
> Update questions doc

- docs/generate_questions_doc.py
- pybatfish/client/commands.py
- pybatfish/client/session.py
- tests/client/test_assert.py
- tests/client/test_questions.py
- tests/client/test_workhelper.py
- tests/question/test_question.py
Add ability to autorun load questions on session creation (but not using in tests or for `bf_session` to preserve old behavior)
> Add ability to autorun load questions on session creation

- pybatfish/client/consts.py
- pybatfish/client/internal.py
- pybatfish/client/resthelper.py
- pybatfish/client/restv2helper.py
- pybatfish/client/session.py
- pybatfish/datamodel/answer/__init__.py
This reverts commit b069cd3cb54825c29f0371d7bf729079868acc80.
until backend is ready :P
> Revert "Use new get answer v2 API (#353)"

- pybatfish/client/_diagnostics.py
- pybatfish/client/commands.py
- pybatfish/client/session.py
- tests/client/test_diagnostics.py
- tests/integration/test_diagnostics.py
Add metadata file (just optional contact info for now) to diagnostics uploads
> Add metadata to diagnostics uploads

- pybatfish/client/session.py
- tests/datamodel/test_session.py
Initialize a new snapshot consisting of a single configuration file with the
given text.
> Session: add init_snapshot_from_text

- pybatfish/datamodel/route.py
- tests/datamodel/test_route.py
Change for batfish/batfish#3719
> Using the non-dataplane BgpRoute in routes datamodel

- pybatfish/client/capirca.py
https://github.com/abseil/abseil-py/issues/99
> capirca: more aggressive abseil workaround

- pybatfish/client/_diagnostics.py
- pybatfish/client/commands.py
> Update dry_run docs to correct False/True

- pybatfish/client/session.py
- pybatfish/datamodel/answer/table.py
- tests/datamodel/answer/test_tableanswerelement.py
Do not rely on magic fields. Fixes #387
> Update table answer detection

- pybatfish/client/asserts.py
- tests/client/test_assert.py
Add no-incompatible-bgp-sessions and no-undefined-references assertions
> Add more asserts

- pybatfish/client/_diagnostics.py
- tests/client/test_diagnostics.py
- tests/integration/test_snapshot_funcs.py
Make some more diagnostics functions 'public'
> Make some more diagnostics functions 'public'

- pybatfish/client/asserts.py
- tests/client/test_assert.py
also reordered assertions and tests alphabetically
> assertion for unreachable filter lines

- pybatfish/client/session.py
Add note about `overwrite` flag to duplicate snapshot error message
> Update duplicate snapshot error message

- pybatfish/client/_facts.py
- pybatfish/client/session.py
- tests/integration/test_facts.py
Remove node spec from validate facts
> Remove node spec from validate facts

- pybatfish/datamodel/referencelibrary.py
- tests/datamodel/test_referencelibrary.py
More PRs to follow for other types
> liberal refbook construction and error messages

- pybatfish/datamodel/primitives.py
- pybatfish/question/question.py
- tests/conftest.py
After https://github.com/batfish/batfish/pull/4234
> add mlag id variable types

- pybatfish/client/extended.py
- pybatfish/client/restv2helper.py
- pybatfish/client/session.py
Use text instead of str for extended object APIs
> Use text instead of str for input type

- pybatfish/client/asserts.py
- pybatfish/client/session.py
> Update asserts arg types

- pybatfish/client/extended.py
- pybatfish/client/restv2helper.py
Bring inline with get_snapshot_object_functions.
> change type annotation: str -> Text

- pybatfish/client/_facts.py
- tests/client/test_facts.py
- tests/integration/facts/expected_facts/basic.yml
- tests/integration/facts/fact_snapshot/configs/basic.cfg
Add initial OSPF process, area, and interface facts to the fact model.
> Add OSPF facts

- pybatfish/client/asserts.py
- pybatfish/client/session.py
- tests/client/test_assert.py
- tests/integration/snapshots/asserts_fail/configs/node.cfg
- tests/integration/snapshots/asserts_fail/configs/remote_node.cfg
- tests/integration/test_asserts.py
Add assertion checking that there are no incompatible/unestablished OSPF sessions, also add relevant tests.
> Add OSPF session assertion

- fix_format.sh
- pybatfish/client/_facts.py
- pybatfish/client/asserts.py
- pybatfish/client/capirca.py
- pybatfish/client/internal.py
- pybatfish/datamodel/answer/table.py
- pybatfish/datamodel/route.py
- pybatfish/exception.py
- setup.py
- tests/client/test_capirca.py
Since not everyone uses Pycharm.
cc: @millstein See if this eases your troubles.
> Add a fix_format script

- pybatfish/client/_facts.py
- tests/client/test_facts.py
Perform validation even when nodes don't exist in actual facts.
> Fix missing node validation

- pybatfish/client/asserts.py
Add OSPF incompatibility assert to set of public assertions.
> Add ospf incompatibility assert

- .buildkite/pipeline.sh
- .idea/inspectionProfiles/Project_Default.xml
Includes tests, mypy checks and pycharm compatibility inspection.
> Stop running legacy python compliance checks

- setup.py
netconan had a bunch of nice improvements since last bump.
> Bump netconan version

- jupyter_notebooks/Getting started with Batfish.ipynb
- tests/integration/facts/expected_facts/basic.yml
> Update node properties

- setup.py
Update setup.py to require python 3.5
> Python requires: 3.5

- pybatfish/client/session.py
- tests/__init__.py
- tests/common_util.py
- tests/integration/test_network_funcs.py
- tests/question/test_question_additional.py
Add annotations for tests requiring specific Bf or Pybf versions
> Add test-version annotations

- pybatfish/client/session.py
- tests/client/test_session.py
Otherwise loading questions fails immediately.
> Session: allow API key specification

- pybatfish/client/extended.py
- pybatfish/client/restv2helper.py
- tests/integration/test_snapshot_funcs.py
Add method to delete snapshot object
> Add method to delete snapshot object

- README.dev.md
Add note about test-version annotations
> Dev readme test annotation note

- pybatfish/datamodel/flow.py
- correct `transitLocation` to `transitLocations`
> Fix PathConstraints docstring

- pybatfish/client/consts.py
- pybatfish/client/internal.py
- pybatfish/client/restv2helper.py
- tests/client/test_questions.py
Allows listing of hidden questions, if required
> Switch to V2 API for question listing

- pybatfish/client/commands.py
Because not everyone uses sessions.
> Proxy param for non-session diagnostic upload

- pybatfish/datamodel/referencelibrary.py
- tests/datamodel/test_referencelibrary.py
- tests/integration/test_network_funcs.py
- tests/integration/test_snapshot_funcs.py
Minor updates to be compatible with updates to the role specification format and role inference in Batfish PR #5209 (currently pending).
> updates for the new roles format and removal of a case-sensitive flag

- .buildkite/pipeline.sh
- setup.py
Because https://github.com/psf/black/issues/1207
> Pin regex again.

- pybatfish/datamodel/flow.py
- tests/datamodel/test_flow.py
> Add match criteria to MatchSessionStepDetail as SessionMatchExpr

- pybatfish/datamodel/flow.py
- tests/datamodel/test_flow.py
I'm not sure if there's any better and simpler notation to represent `ForwardOutInterface`, please let me know if there's any suggestions.
> Add SessionAction and include it in MatchSessionStepDetail

- pybatfish/datamodel/flow.py
- tests/datamodel/test_flow.py
> Add step details parsing for SetupSessionStep

- setup.py
> Pin nbformat

- pybatfish/util.py
> Remove deprecated html escaping code

- pybatfish/client/capirca.py
- pybatfish/client/commands.py
- pybatfish/client/session.py
- pybatfish/datamodel/flow.py
- pybatfish/datamodel/referencelibrary.py
- pybatfish/question/question.py
- pybatfish/util.py
- requirements.txt
- setup.py
- tests/client/test_assert.py
- tests/client/test_capirca.py
- tests/client/test_facts.py
- tests/client/test_session.py
- tests/client/test_workhelper.py
- tests/integration/test_notebook.py
- tests/question/test_question.py
No longer needed since project is python 3 only.
> Remove all occurrences of six library

- .buildkite/build_docs.sh
- .buildkite/pipeline.sh
Minimal overhead, but ensures our documentation actually compiles.
> Ensure we can build documentation as part of pre-commit

- pybatfish/datamodel/flow.py
> Fix docstring for PathConstraints

- docs/source/getting_started.rst
- docs/source/index.rst
Note: this PR is going into `new-docs` branch.
View html version here: https://pybatfish.readthedocs.io/en/add-doc-skeleton/getting_started.html
After merge, will be visible here: https://pybatfish.readthedocs.io/en/new-docs/
> Add skeleton for new docs

- pybatfish/datamodel/acl.py
- pybatfish/datamodel/answer/base.py
- tests/datamodel/test_acltrace.py
- tests/datamodel/test_traceelement.py
Example output in console:
Example output in Jupyter notebook:
> TraceTree dataclasses and representations

- docs/source/index.rst
- docs/source/supported_devices.rst
- docs/source/system_req.rst
Note: this PR is going into the `new-docs` branch.
> New docs: add supported devices and system requirements

- jupyter_notebooks/Analyzing ACLs and Firewall Rules.ipynb
AclTracer: don't trace default deny
> update refs for batfish PR 5452

- docs/nb_gen/schema.py
- docs/nb_gen_tests/test_schema.py
- docs/requirements.txt
- setup.py
Will be used in notebook generation.
> New docs: add schema conversion code

- docs/source/_static/custom.css
- docs/source/conf.py
> New docs: wider theme

- docs/nb_gen/questions.yaml
- docs/nb_gen_tests/test_schema.py
- docs/requirements.txt
- setup.py
This YAML is the source of truth on how questions are grouped into
categories and how they are executed (on which snapshots and with which
parameters).
Also adding tests that the YAML conforms to a given schema.
> New docs: Add question yaml

- pybatfish/client/commands.py
- tests/integration/test_answer_funcs.py
Remove old code dealing with init'ing and running of analyses.
It is unused, undocumented and untested.
> Delete bf*_analysis code

- docs/nb_gen/__main__.py
- docs/nb_gen/base-question-notebook.ipynb
- docs/nb_gen/gen_question_notebooks.py
- docs/nb_gen/questions.yaml
- docs/nb_gen_tests/conftest.py
- docs/nb_gen_tests/test_notebook.py
- docs/nb_gen_tests/test_schema.py
- docs/source/index.rst
- docs/source/notebooks/configProperties.ipynb
- docs/source/questions.rst
* Add notebook generation code
* Notebook tests
* First auto-generated notebook (containing just one question as a PoC)
Preview [docs here](https://pybatfish.readthedocs.io/en/add-config-props-notebook/notebooks/configProperties.html)
> New docs: add configProperties notebook

- jupyter_notebooks/Analyzing ACLs and Firewall Rules.ipynb
- jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb
- jupyter_notebooks/Getting started with Batfish.ipynb
- jupyter_notebooks/Introduction to Forwarding Analysis.ipynb
- jupyter_notebooks/Introduction to Forwarding Change Validation.ipynb
- jupyter_notebooks/Introduction to Route Analysis.ipynb
- jupyter_notebooks/Provably Safe ACL and Firewall Changes.ipynb
- jupyter_notebooks/Safely refactoring ACLs and firewall rules.ipynb
- jupyter_notebooks/Validating Configuration Settings.ipynb
The original link had (inexplicably) expired.
> update the slack link on notebooks

- docs/nb_gen/doc_tables.py
- docs/source/notebooks/configProperties.ipynb
Default value existing implies paramter is optional
> New docs: fix parameter optionality

- docs/nb_gen_tests/test_notebook.py
- docs/source/advanced.rst
- docs/source/notebooks/references.ipynb
[Preview here](https://pybatfish.readthedocs.io/en/references-nb/notebooks/references.html)
🤷‍♂
> New docs: add the reference library notebook

- jupyter_notebooks/Analyzing ACLs and Firewall Rules.ipynb
- jupyter_notebooks/Provably Safe ACL and Firewall Changes.ipynb
- jupyter_notebooks/Safely refactoring ACLs and firewall rules.ipynb
- tests/integration/test_notebook.py
In prep for new docs, where notebooks can be inlined.
> Switch to absolute links in notebooks

- docs/nb_gen_tests/test_notebook.py
- docs/source/index.rst
- docs/source/notebooks/linked/analyzing-acls-and-firewall-rules.ipynb
- docs/source/notebooks/linked/analyzing-the-impact-of-failures-and-letting-loose-a-chaos-monkey.ipynb
- docs/source/notebooks/linked/getting-started-with-batfish.ipynb
- docs/source/notebooks/linked/introduction-to-bgp-analysis.ipynb
- docs/source/notebooks/linked/introduction-to-forwarding-analysis.ipynb
- docs/source/notebooks/linked/introduction-to-forwarding-change-validation.ipynb
- docs/source/notebooks/linked/introduction-to-route-analysis.ipynb
- docs/source/notebooks/linked/provably-safe-acl-and-firewall-changes.ipynb
- docs/source/notebooks/linked/safely-refactoring-acls-and-firewall-rules.ipynb
- docs/source/notebooks/linked/validating-configuration-settings.ipynb
- docs/source/public_notebooks.rst
- jupyter_notebooks/Introduction to Forwarding Analysis.ipynb
- jupyter_notebooks/Introduction to Route Analysis.ipynb
- jupyter_notebooks/Safely refactoring ACLs and firewall rules.ipynb
Note: public notebooks needed small formatting changes to comply with common markdown.
[Preview here](https://pybatfish.readthedocs.io/en/linked-nbs/public_notebooks.html)
> New docs: inline public jupyter notebooks

- docs/nb_gen_tests/test_schema.py
1. Blacklist some questions
2. Ensure blacklisted questions are not documented
> Better test for YAML question inventory

- docs/source/formats.md
- docs/source/getting_started.rst
1. Add more instructions from the wiki
1. Fix up some nits
2. Fix links and make use of warning/note boxes
> New docs: Beef up the formats section

- docs/nb_gen_tests/test_schema.py
This prevents new undocumented questions.
> New docs: scoped xfail

- docs/source/notebooks/linked/analyzing-public-and-hybrid-cloud-networks.ipynb
- docs/source/public_notebooks.rst
- jupyter_notebooks/Analyzing public and hybrid cloud networks.ipynb
Also includes fixing the headings.
> New docs: document AWS notebook

- .buildkite/doc_tests.sh
- .buildkite/integration_tests.sh
- .buildkite/pipeline.sh
Hopefully will speed up the builds a bit
> Test docs in separate pipeline step

- jupyter_notebooks/Analyzing ACLs and Firewall Rules.ipynb
- jupyter_notebooks/Analyzing public and hybrid cloud networks.ipynb
- jupyter_notebooks/Provably Safe ACL and Firewall Changes.ipynb
- pybatfish/datamodel/acl.py
- pybatfish/datamodel/answer/base.py
- tests/datamodel/test_acltrace.py
HTML output in Jupyter notebook:
Text output:
> Add List<TraceTree> schema support with pretty console and html output

- .buildkite/doc_tests.sh
- docs/source/notebooks/configProperties.ipynb
- docs/source/notebooks/filters.ipynb
We were getting false positive passes.
> Fix doctests

- pybatfish/client/restv2helper.py
- tests/client/test_restv2helper.py
* Make v2 http requests use the requests session defined in v2 helper
* Add v2 API header helper
> Make v2 API requests use correct requests session

- pybatfish/client/commands.py
- pybatfish/client/consts.py
- pybatfish/client/workhelper.py
> Remove killwork API

- docs/README.md
otherwise module is not discovered correctly
> Fix readme for doc generation

- pybatfish/client/_diagnostics.py
- setup.py
- tests/client/test_diagnostics.py
Fixes https://github.com/batfish/pybatfish/issues/642
> Diagnostics: retry failed uploads

- docs/source/notebooks/filters.ipynb
After https://github.com/batfish/batfish/pull/5920
> Update searchfilters docs

- tests/integration/test_diagnostics.py
Make diagnostics upload test compatible with older versions of Pybatfish by setting up session with retry in test file instead of relying on it to exist in upload module.
> Diagnostics test compatibility

- docs/source/notebooks/filters.ipynb
> Update testfilter docs

- docs/source/formats.md
Add instructions for pulling configs through Panorama
> Docs: PAN: Add instructions for Panorama

- .buildkite/pipeline.sh
- setup.py
Pin `black` to 19.10b to keep formatting the same
> Pin black version

- pybatfish/client/commands.py
- pybatfish/client/session.py
- tests/integration/test_network_funcs.py
* Move logic out of `commands` into `Session` class
* Update tests to use `session`
> Auto-complete: move logic into Session

- docs/environment.yml
> Bump pip on read-the-docs

- docs/source/notebooks/linked/analyzing-routing-policies.ipynb
- docs/source/public_notebooks.rst
- jupyter_notebooks/Analyzing Routing Policies.ipynb
- jupyter_notebooks/README.md
- jupyter_notebooks/startup.py
- tests/integration/test_notebook.py
Waiting on selective notebook testing or BgpRouteConstraints making it to prod release.
> Add routing nb

- tests/integration/test_facts.py
The example network configs and parsing have changed in a way that requires new Batfish.
> test_facts: restrict to dev

- docs/nb_gen/base-question-notebook.ipynb
- docs/nb_gen/gen_question_notebooks.py
- docs/nb_gen/schema.py
- docs/nb_gen_tests/test_notebook.py
- docs/source/notebooks/configProperties.ipynb
- docs/source/notebooks/differentialQuestions.ipynb
- docs/source/notebooks/filters.ipynb
- docs/source/notebooks/forwarding.ipynb
- docs/source/notebooks/ipsec.ipynb
- docs/source/notebooks/resolvingSpecifiers.ipynb
- docs/source/notebooks/routingProtocols.ipynb
- docs/source/notebooks/routingTables.ipynb
- docs/source/notebooks/snapshot.ipynb
- docs/source/notebooks/topology.ipynb
- docs/source/notebooks/vxlan_evpn.ipynb
- jupyter_notebooks/Analyzing ACLs and Firewall Rules.ipynb
- jupyter_notebooks/Analyzing Routing Policies.ipynb
- jupyter_notebooks/Analyzing public and hybrid cloud networks.ipynb
- jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb
- jupyter_notebooks/Getting started with Batfish.ipynb
- jupyter_notebooks/Introduction to BGP Analysis.ipynb
- jupyter_notebooks/Introduction to Forwarding Analysis.ipynb
- jupyter_notebooks/Introduction to Forwarding Change Validation.ipynb
- jupyter_notebooks/Introduction to Route Analysis.ipynb
- jupyter_notebooks/Provably Safe ACL and Firewall Changes.ipynb
- jupyter_notebooks/Safely refactoring ACLs and firewall rules.ipynb
- jupyter_notebooks/Validating Configuration Settings.ipynb
- tests/integration/test_notebook.py
Goal: reduce churn during regeneration, editing, etc.
> notebooks: clean up metadata

- docs/requirements.txt
https://github.com/spatialaudio/nbsphinx/issues/549
> Pin docutils to 0.16

- docs/source/specifiers.md
- copy changes from batfish/batfish#6856
> update specifiers.md per batfish/batfish#6856

- docs/environment.yml
- docs/requirements.txt
> Remove recommonmark from docs environment

- pybatfish/datamodel/flow.py
Transit, forbidden, and end locations are node level.
> Update doc for path constraint

- docs/source/notebooks/routingProtocols.ipynb
Updates the SearchRoutePolicies documentation due to the updates from batfish PR 7094.
> Update the SearchRoutePolicies documentation

- pybatfish/datamodel/flow.py
- tests/datamodel/test_flow.py
- EnterFromVxlanTunnel
- ExitIntoVxlanTunnel
> Add support for VXLAN tunnel traceroute steps

- .buildkite/pipeline.sh
- .pre-commit-config.yaml
Revert "ci: disable isort in attempt to workaround build failure (#805)"
This reverts commit c239cb61a8480aaef94053e9e41b2cc2fd224884.
> ci: restore isort with blocking virtualenv upgrade

- .buildkite/pipeline.sh
Per https://github.com/pypa/virtualenv/issues/2257, new version has
been released.
> ci: remove pinning of virtualenv

- docs/source/notebooks/routingTables.ipynb
> Update routes questions docs after default specification

- tests/integration/test_facts.py
- update min bf version since fact values changed after batfish/batfish#7939
> update requires for integration tests after batfish/batfish#7939

- pybatfish/datamodel/flow.py
- tests/datamodel/test_flow.py
This reverts commit 01162b53a81579aee6a5164fde0cd6b12ba79fe8.
We never ended up using them.
> Revert "Add support for VXLAN tunnel traceroute steps (#789)"

- docs/nb_gen/questions.yaml
- docs/source/notebooks/topology.ipynb
(Additional doc changes coming in a separate PR.)
> Docs: Add user provided L1

- jupyter_notebooks/Pandas Examples.ipynb
Fixes https://github.com/batfish/pybatfish/issues/838
> Use <code> to counter interaction between backtics and links

- docs/source/notebooks/configProperties.ipynb
> re-render notebooks after batfish/batfish#8400

- jupyter_notebooks/Introduction to Forwarding Analysis.ipynb
> notebook: remove one more ga-beacon

- pybatfish/client/asserts.py
- tests/client/test_assert.py
Fixes https://github.com/batfish/batfish/issues/5863
Cc: @JulioPDX
> Fix route assertions

- README.dev.md
- setup.cfg
> building: py3 only, also source dist

- jupyter_notebooks/Analyzing Routing Policies.ipynb
- jupyter_notebooks/networks/route-analysis/configs/border1.cfg
- jupyter_notebooks/networks/route-analysis/configs/border2.cfg
> Fix RFC1918 space

- docs/nb_gen_tests/test_schema.py
The question was newly created and there is no documentation yet.
> Exclude compareRoutePolicies question from docs

- .github/workflows/reusable-precommit.yml
> pybatfish: remove tests of deprecated API

- docs/source/notebooks/routingProtocols.ipynb
Updates the documentation of the searchRoutePolicies question to reflect the new perPath parameter ([batfish/batfish#8622](https://github.com/batfish/batfish/pull/8622))
> Docs: Update the searchRoutePolicies documentation to add a new parameter

- pybatfish/client/_diagnostics.py
- pybatfish/client/resthelper.py
- pybatfish/client/restv2helper.py
- tests/client/test_diagnostics.py
- tests/client/test_resthelper.py
- tests/client/test_restv2helper.py
See: https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html
> urllib3: upgrade to allowed_methods

- jupyter_notebooks/README.md
> Fix pointer to cloud network

- docs/nb_gen_tests/test_schema.py
- docs/source/notebooks/configProperties.ipynb
Need to update after https://github.com/batfish/batfish/pull/8735
The id field in the notebook cells was auto-generated despite a brand new Python 3.9 environment with only pybatfish, requriments.txt and docs/requirements.txt.  
Update: Happens with Python 3.7 as well. (Some notebook dependency must have changed.)
> Update configProperties questions notebook

- jupyter_notebooks/Introduction to BGP Analysis.ipynb
Update a notebook's output to reflect recent Batfish updates.
> Notebook: Fix a CI issue

- docs/nb_gen_tests/test_schema.py
- docs/source/notebooks/routingTables.ipynb
Cluster list is a set, not a list.
Undocumented new question.
> docs: update tests after recent work

- docs/source/formats.md
> Fixed typo in formats.md

- docs/nb_gen/schema.py
- docs/source/notebooks/routingProtocols.ipynb
- pybatfish/datamodel/primitives.py
- pybatfish/datamodel/route.py
- pybatfish/question/question.py
- tests/datamodel/test_route.py
The pybatfish counterpart to Batfish PR [8987](https://github.com/batfish/batfish/pull/8987)
> TestRoutePolicies: Add optional parameter for BGP session properties

- .github/workflows/reusable-precommit.yml
> upload the built docs

- pybatfish/client/restv2helper.py
- pybatfish/client/session.py
- pybatfish/datamodel/referencelibrary.py
- setup.py
- tests/datamodel/test_referencelibrary.py
- tests/integration/test_network_funcs.py
- tests/integration/test_snapshot_funcs.py
**Stack**:
- #913
- #912
- #911 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
> pybatfish: delete everything deprecated

- .github/workflows/reusable-precommit.yml
**Stack**:
- #912
- #914 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
> CI: upgrade to java 17

- docs/source/getting_started.rst
Remove port 9997 from the documentation
> Remove port 9997 from the docs

- .pre-commit-config.yaml
**Stack**:
- #944
- #943
- #945 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
> Swap precommit mirror
