batfish/pybatfish

.travis/build.sh
- Since the notebook is importing commands in an external script `startup.py`, flake throws a warning like:
```
stdin:8:1: F821 undefined name 'get_ipython'
stdin:18:1: F821 undefined name 'bf_set_network'
stdin:19:1: F821 undefined name 'bf_init_snapshot'
stdin:31:14: F821 undefined name 'bfq'
stdin:56:11: F821 undefined name 'pd'
```
=> Configuring flake for Notebooks

pybatfish/client/resthelper.py, pybatfish/client/workhelper.py
The code expects that there's always a snapshot present on work items. Enforce this, and use the
correct snapshot when fetching logs.
Alternate approach to #37  -- thoughts?
=> workhelper: require snapshot set on executed work items

jupyter_notebooks/Test and Validation.ipynb, tests/integration/test_notebook.py
Follow-up from batfish/pybatfish#40:
- comparing explicit fields for outputs as comparing the entire output makes the result indeterministic because of the underlying dict structure
- Using `pd.concat` in one of the cells to make the column order deterministic
=> Fixing notebook tests

jupyter_notebooks/Getting started with Batfish.ipynb, jupyter_notebooks/Test and Validation.ipynb, pybatfish/client/commands.py, pybatfish/question/question.py, pybatfish/util.py
- if background is True, semantics unchanged
- if initialization fails, then:
- do not change bf_session settings
- raise an exception
- if initialization succeeds, return the name of the created
snapshot (and set bf_session correctly).
includes #39, so ignore that bit. Thoughts on what I think are the improved semantics?
=> Client: cleanup bf_init_snapshot signature and postconditions

docs/source/questions-generated.rstgen, pybatfish/question/question.py, tests/question/test_question.py
- ensure that descriptions all end with period and strip variables
- sort variables that are required first in the list
- remove duplicate spaces from the generated parameter string
=> Clean up docstrings

tests/integration/test_notebook.py
This will exclude checkpoints dir when the tests are being run locally. git repo anyways does not have `.ipynb_checkpoints` dir
=> Excluding .ipynb checkpoint dir and use better variable names while doing assertion

pybatfish/question/question.py, pybatfish/util.py, requirements.txt, setup.py, tests/datamodel/test_datamodel_element.py
* Get rid of jsonpickle module
* Move out `_QuestionEncoder` -> `BfJsonEncoder` as a general utility for serializing all question and datamodel classes
* Trivial tests
=> Generalize serialization

docs/source/quickstart.rst
- Fixed params like `nodeRegex, interfaceRegex`.
- fixed statements like `ans['rows']` which don't work now.
- removed questions like `nodeProperties` producing huge outputs and instead using questions with smaller readable outputs.
- removed/modified other parts for streamlining.
=> Some modifications in quick-start

.travis/build.sh
Really hope this is a temporary issue; 
Affects only new, from scratch installs of jupyter, jupyter-console,  and thus ipython.
cc @sfraint since you were the one who discovered it.
=> Temp fix build by installing ipython < 7 on travis

pybatfish/datamodel/answer/table.py
Per discussion, this makes the notebook rendering nicer when you don't call `.frame()`, and should have no effect on other clients.
=> TableAnswer: delegate _repr_html_ too

pybatfish/client/commands.py, pybatfish/client/consts.py, pybatfish/client/resthelper.py, pybatfish/client/workhelper.py
Switch to using getAnswer and getAnalysis answer instead.
This change should be transparent to users, however it does affect developers a little: `work_helper.execute` method no longer fetches the answer/log produced during the execution of the workitem. 
This means that `dataplaneAnswerElement`, for example, won't be fetched and printed like it was previously, when running `bf_generate_dataplane()`
=> Replace uses of get_object API call and deprecate it

pybatfish/question/question.py, pybatfish/util.py, tests/question/test_question.py, tests/question/test_question_additional.py
Since JsonPath isn't used anymore and validating these in python land was error prone anyway.
=> Remove validation of JsonPath regexes

pybatfish/question/question.py, tests/question/test_question.py
=> question: if name is not provided, use a transient name

pybatfish/client/commands.py, pybatfish/client/consts.py, pybatfish/client/restv2helper.py
Admittedly, a very developer-centric behavior but needed until we have better designed APIs.
Tested manually to avoid crafting and checking in failure configs.
=> Print Java log upon bf_init_snapshot failure

pybatfish/client/workhelper.py
Catch requeue failures (e.g. implicit dataplane generation fails) and add more exception details.  It's not very pretty, but gives some much needed insight into these sort of failures.
For example, with https://github.com/batfish/batfish/pull/2630:
```
>>> bfq.traceroute(...) # Fails implicit dataplane generation
{'answerElements': [{'class': 'org.batfish.datamodel.answers.StringAnswerElement',
'answer': 'Not answered'}],
'status': 'NOTFOUND',
'summary': {'numFailed': 0, 'numPassed': 0, 'numResults': 0}}
```
becomes:
```
>>> bfq.traceroute(...) # Fails implicit dataplane generation
BatfishException: Work finished with status REQUEUEFAILURE
work_item: {"containerName": "example_network", "id": "51db944d-21e1-47ef-bc23-6c049773f249", "requestParams": {"answer": "", "questionname": …
```
=> Handle another failed task status

pybatfish/datamodel/__init__.py
This enables one `from pybatfish.datamodel import *` statement to get all datamodel classes.
=> Simplify (pull up) datamodel imports

tests/datamodel/test_datamodel_element.py
Update json serialization test to no longer depend on key ordering.
Should fix non-deterministic failures when comparing json serializations, see https://travis-ci.com/batfish/pybatfish/jobs/163127807
=> Update json serialization test

pybatfish/client/diagnostics.py, pybatfish/client/restv2helper.py
1. Fix mutable default args (see: https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments)
2. Remove unused parameter
=> pybatfish: fix mutable default args and unused params

pybatfish/datamodel/flow.py
We had incorrect name in the set of success dispositions
=> Fix color for delivered to subnet

.travis/build.sh, README.dev.md, requirements.txt, setup.py
* No need to split dev and test extras. All devs should test
* Update dev readme
* Put pytest as a proper dev dependency: `tests_require` does **not** install the
dependencies, but .travis/build assumes pytest is installed
* Travis scripts: use newer `pytest` instead of `py.test`
* Pin more dependencies: sphinx, netconan
cc: @sfraint
=> setup.py and testing improvements

pybatfish/client/commands.py, pybatfish/client/diagnostics.py, pybatfish/client/internal.py, pybatfish/client/workhelper.py, pybatfish/question/question.py, tests/client/test_commands.py, tests/client/test_workhelper.py
These are plumbed through to `WorkItem.requestParams`,
just like `bf_session.additionalArgs`. However, per-call
arguments are temporary and take precedence over
the session args.
=> pybatfish: add extra_args to WorkItem executors

pybatfish/client/diagnostics.py
Remove redundant diagnostic questions, specifically parse and convert warnings which overlap with the new `initIssues` question.
=> Remove redundant diagnostic questions

pybatfish/client/workhelper.py
This will terminate short work items much more quickly, but will also check status (and print) up to 4 more times than before where we always slept every second:
* 0s [happened before after 0s cumulative sleep]
* 0.1s
* 0.25s
* 0.48s
* 0.81s
* 1.32s  [happened before after 1s cumulative sleep]
* 2.08s  [happened before after 2s cumulative sleep]
* 3.08s  [happened before after 3s cumulative sleep]
* ...
=> workhelper: ramp up sleeping to 1s

pybatfish/client/commands.py, pybatfish/client/resthelper.py, pybatfish/client/restv2helper.py, pybatfish/client/session.py, pybatfish/client/workhelper.py, pybatfish/client/workitem.py, pybatfish/question/question.py, tests/client/test_workhelper.py, tests/integration/test_answer_funcs.py
* Accept simple constructor params
* Update to use snake_case
* Support old param names for reverse compatibility, w/deprecated warning
New style:
```
> %run startup.py
> s = Session(bf_logger, host='example.com', ssl=True)
```
or
```
> %run startup.py
> bf_session.host = 'example.com'
> bf_session.ssl = True
```
But old style code still works:
```
> %run startup.py
> bf_session.coordinatorHost = 'example.com'
DeprecationWarning: Call to deprecated function (or staticmethod) coordinatorHost. (Use host)
> bf_session.useSsl = True
DeprecationWarning: Call to deprecated function (or staticmethod) useSsl. (Use ssl)
```
=> Update Session constructor params and vars

docs/generate_questions_doc.py
Session no longer takes in a logger, so no longer pass one in during setup for question doc generation.
=> Update Session creation for doc generation

pybatfish/client/commands.py, pybatfish/client/diagnostics.py, pybatfish/client/session.py
* Moved functionality for some `bf_<cmds>` in `commands.py` into `Session` object
* Removed background flag from public, replacement methods
* Consolidated some `get_node_role...` functions down into two core functions (`get_node_role_dimension`, `get_node_roles`)
* A few docstring updates at the same time, more to come in the future
Deferred `@deprecated` annotation for now, to avoid affecting notebooks
=> Initial migration of bf_cmd functionality into Session

pybatfish/client/_diagnostics.py, pybatfish/client/session.py, tests/client/test_diagnostics.py, tests/integration/test_diagnostics.py, tests/integration/test_snapshot_funcs.py
* Make `diagnostics` module "private"
* Update functions in `diagnostics` module to use better "public" / "private" naming (e.g. `upload_diagnostics` is exposed to be used elsewhere in Pybatfish, so make it "public")
=> Update module and func names for diagnostics

pybatfish/client/session.py, pybatfish/question/question.py, tests/client/test_questions.py
* Add `Questions` class with question functions (list, load, list_tags)
* When called, load questions will load into `Questions` obj inside `Session` instead of `bfq`
* Add some basic tests
Now, you can run:
```
> bf = Session()
> bf.set_network(NETWORK_NAME)
> bf.init_snapshot(...)
'snapshot_name'
> bf.q.load()
> bf.q.list()
[{'name': 'qName', ...
> bf.q.nodeProperties().answer()
<table answer>
```
old-style usage still works as well:
```
> bf_set_network(NETWORK_NAME)
> bf_init_snapshot(...)
'snapshot_name'
> load_questions()
> list_questions()
[{'name': 'qName', ...
> bfq.nodeProperties().answer()
<table answer>
```
=> Add question functions into Session

pybatfish/client/asserts.py, tests/client/test_assert.py
Update asserts to accept session param where applicable.
Running:
```
assert_filter_permits('filter', headers)
```
behaves as it used to, using the question in `bfq` (and underlying Session `bf_session`) to answer question and perform the assert
Running:
```
assert_filter_permits('filter', headers, session=bf)
```
uses question defined in `bf.q` object (and underlying Session `bf`) to answer question and perform the assert
=> Update asserts to accept session

pybatfish/datamodel/referencelibrary.py, tests/datamodel/test_referencelibrary.py
The following example will work after https://github.com/batfish/batfish/pull/3615
`refbook = ReferenceBook("book1", addressGroups=[{"g1", "addresses": ["1.1.1.1"], childGroupNames=["g2"]}, {"g2", addresses=["2.2.2.2"]}])`
=> child addressgroups

pybatfish/client/workhelper.py, tests/client/test_workhelper.py
1. `obtainedTime` is not obtained from server, it's obtained from user (aka, task creation). Fix the tests to match reality
2. Since we have the initial start time, print total elapsed time.
3. Minor improvements to output (period).
And fixed up tests.
```
status: TRYINGTOASSIGN
.... no task information
status: ASSIGNED
.... Mon Apr 15 17:56:14 2019 PDT Begin job.
status: ASSIGNED
.... Mon Apr 15 17:56:14 2019 PDT Begin job.
status: ASSIGNED
.... Mon Apr 15 17:56:14 2019 PDT Begin job.
status: ASSIGNED
.... Mon Apr 15 17:56:14 2019 PDT Parse network configs 16 / 95.
status: ASSIGNED
.... Mon Apr 15 17:56:14 2019 PDT Parse network configs 46 / 95.
status: CHECKINGSTATUS
.... Mon Apr 15 17:56:14 2019 PDT Parse network configs 84 / 95.
status: CHECKINGSTATUS
.... Mon Apr 15 17:56:14 2019 PDT …
```
=> workhelper: better debug timings

pybatfish/datamodel/route.py, tests/datamodel/test_route.py
This reverts commit 317954300b88ab4e3acf5c749cf03977124bb4b0.
But the backend will accept class field (batfish/batfish#3725)
=> Revert "change for batfish/batfish#3719 (#359)"

pybatfish/client/capirca.py, setup.py
* `ipaddr` module is obsolete: https://pypi.org/project/ipaddr/
* Tweak setup.py to install `ipaddress` backport for 2.7
=> Switch to using stdlib's ipaddress

setup.py
Matplotlib dropped support for py3.5 in v3.1
We should too, eventually, but for now pin matplotlib to before 3.1.0
=> Pin matplotlib

pybatfish/client/session.py, pybatfish/client/workhelper.py
1. Use context managers (i.e., actually close our files)
2. Do not re-open the same temp file
Resolves batfish/batfish#3922
=> Be more cautious with temp files on init_snapshot

.buildkite/pipeline.sh, docs/source/quickstart.rst, pybatfish/client/commands.py
1. Bring back doctests, fix up (or skip) whatever is broken
2. Tweak wording in the getting started guide to include `set_network` and naming of the snapshot
=> Bring back doctest, tweak getting started guide

pybatfish/client/session.py, tests/client/test_assert.py
Add the ability to run `asserts` from a session object, e.g.:
```
bf = Session()
assert_result = bf.asserts.assert_no_undefined_references(soft=True)
```
versus previous method (which still works):
```
bf = Session()
assert_result = assert_no_undefined_references(session=bf, soft=True)
```
Also add expand assert tests to cover these new calls.  This PR just add the shallow wrapper functions and does _not_ update assert docstrings - that can be done in a separate pass.
=> Add asserts to Sessions

pybatfish/client/_facts.py, tests/client/test_facts.py
Add option to return all validated properties, not just mismatched properties.  Useful for seeing _all_ properties that were checked.
=> Add verbose validate_facts option

pybatfish/client/session.py, setup.py, tests/client/test_session.py
Support recognizing `batfish_session` `entry_points` specified in `setup.py`
Also allow user to build a `Session` object by specifying the type and object params, e.g.: `Session.get('bf', load_questions=False)`
=> Support Session entry_points

.buildkite/pipeline.sh, setup.py
4.0.0 dropped support for legacy python
@dhalperi @sfraint We **need** to start letting people know we're going to drop support for py2, in our documentation and examples, otherwise we're digging ourselves into a hole where all the libraries we use are going to be outdated.
=> Pin pydocstyle

setup.py
Add indication that Pybatfish supports type hinting ([PEP561](https://www.python.org/dev/peps/pep-0561/)).
=> Add indication that Pybatfish supports type hinting

jupyter_notebooks/Analyzing ACLs and Firewall Rules.ipynb
Address several small nits in the "Analyzing ACLs and Firewall Rules" notebook:
- Typo when referring to NFS.
- Sort output of `filterLineReachability` question so it is as described in the text; without this change, the order is wrong.
=> Tiny Jupyter notebook fixes

pybatfish/client/asserts.py, tests/integration/snapshots/asserts/configs/node.cfg, tests/integration/test_asserts.py
Old style BGP session status specifier broke recently (probably related to https://github.com/batfish/batfish/pull/4240), so use the new format (`/` enclosed regex).
Also, add some basic e2e tests for all asserts.
=> Update assert specifier

pybatfish/client/asserts.py, tests/integration/snapshots/asserts_fail/configs/node.cfg, tests/integration/snapshots/asserts_fail/configs/remote_node.cfg, tests/integration/test_asserts.py
Update `bgp` status spec to work with new substring semantics in `Batfish` (previous PR just fixed the regex syntax, not it's correctness).
Flesh out more `pybatfish.client.asserts` tests:
* Add BGP sessions with `unknown remote` to passing test config (these should be filtered out by default status spec)
* Add some e2e tests for failing asserts
=> Update bgp status spec and add more assert tests

pybatfish/client/asserts.py, pybatfish/client/session.py
Filter BGP session status in Pybatfish instead of in backend by default.
This improves reverse compatibility (since the regex was not compatible with older Batfish, like the current Docker container).
=> Update no incompat BGP sessions assert

pybatfish/client/restv2helper.py, pybatfish/client/session.py, tests/integration/test_session.py
Use new version API for fetching component version (e.g. Batfish, Z3) and add simple integration test
=> Use new version API

pybatfish/client/session.py
Make invalid session type error a little prettier.
When an invalid session type is specified, the error was:
```
ValueError: Invalid session type.
Specified type 'bogus' does not match any registered session type: dict_keys(['bf'])
```
with this PR it is:
```
ValueError: Invalid session type.
Specified type 'bogus' does not match any registered session type: {'bf'}
```
=> Improve session error message

pybatfish/datamodel/flow.py
Simplified documentation, less confusion.
Only used in _really_ old questions (if any)
=> Hide old flow classes from __all__

tests/integration/facts/expected_facts/basic.yml, tests/integration/test_facts.py
Remove `point_to_point` bool from expected facts (see https://github.com/batfish/batfish/pull/4481) and make failed test output more human-readable
=> Update validated OSPF facts

pybatfish/datamodel/primitives.py, pybatfish/question/question.py, tests/conftest.py
OSPF session status spec was added in https://github.com/batfish/batfish/pull/4694, update param validation to support this.
=> Add support for OSPF session status spec param type

pybatfish/client/extended.py, pybatfish/client/restv2helper.py
Update types used in `extended` functions, prefer `Text` over `str` (finishing changed started in https://github.com/batfish/pybatfish/pull/425).
=> Update extended method types

pybatfish/client/capirca.py, setup.py
In the latest release of absl-py common library, Google fixed the logging
mess. Force a minimum version of that library and remove the hack.
https://github.com/abseil/abseil-py/issues/99
=> Remove Capirca/absl-py workaround

pybatfish/client/_facts.py, pybatfish/util.py
Since we're no longer supporting `Python2`, import from `collections` using `Python3`-preferred, non-deprecated method
Avoids the `DeprecationWarning`:
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```
=> Update collections import

tests/integration/test_facts.py
Specify snapshot name instead of using last element of `list_snapshot` to get previous snapshot
=> Fix flaky test

tests/common_util.py
Improve skip message for failed version check
Previously, the message showed something like:
`Pybatfish version too low ((1, 2, 3) < 2019.10.28)`
Now it shows:
`Pybatfish version too low (1.2.3 < 2019.10.28)`
=> Update version-check test-skip-message

tests/integration/test_asserts.py
separating out duplicate router IDs test from common pass/fail assertion tests so that they can be annotated with `@requires_bf`
=> Adding version guard for no duplicate router IDs assert

pybatfish/client/_diagnostics.py, pybatfish/client/session.py
Helps users upload diagnostics if required to use a corp
proxy.
Proxy settings apply only for diagnostic upload only.
Slack thread for reference: https://batfish-org.slack.com/archives/C8XKQNHAQ/p1573621823217700
=> Upload diagnostics: add optional proxy URL

pybatfish/client/_diagnostics.py
As @eidorb correctly points out in #503, previous fix erroneously overrides proxy env vars if they are set.
This fixes it up: propagate proxy dict to callees only if the proxy URL was explicitly set. Otherwise `requests` will pick up the `HTTPS_PROXY` var.
@dhalperi manual testing procedure https://docs.google.com/document/d/1WbjcjjvCR6A4iB06CjZElfro0rlgEBgAzjfR478ktxQ/edit
=> Diagnostics: do not clobber proxies defined in environment

tests/integration/test_network_funcs.py, tests/integration/test_snapshot_funcs.py
Since some of the functionality is backwards-incompatible, mark it as such in tests.
Also delete a useless role inference test.
Build here: https://buildkite.com/intentionet/open-source-docker-pipeline/builds/325
Deferring cleanup till later.
=> Fix role tests

pybatfish/datamodel/flow.py, tests/datamodel/test_flow.py
Session action and match criteria are trickier since they involve creating new data classes, so I'm breaking them into different PRs.
For the `MatchSessionStepDetail` in this PR, an example output would be:
=> Add incoming interfaces and transformation to MatchSessionStepDetail

jupyter_notebooks/Analyzing ACLs and Firewall Rules.ipynb, jupyter_notebooks/Provably Safe ACL and Firewall Changes.ipynb, pybatfish/datamodel/acl.py, tests/datamodel/test_traceevent.py
We only care about the description, so ignore any other fields.
If description is missing, exclude the event from the trace.
=> Simplify AclTraceEvent

.readthedocs.yml, docs/requirements.txt
It's more flexible than the web interface, and can be versioned.
Also, adding an additional requirements file as part of prep work for #541
=> Add readthedocs config as a yaml file

.pre-commit-config.yaml, docs/source/advanced.rst, docs/source/conf.py, docs/source/index.rst, docs/source/specifiers.md, tests/docs/test_docs.py
* Enables using markdown in sphinx builds w/ recommonmark
* Add specifiers.md that is a mirror of parameters.md
* Add test to check that batfish's parameters.md and specifiers.md is in sync
Preview HTML here:
https://pybatfish.readthedocs.io/en/add-specifiers/advanced.html
https://pybatfish.readthedocs.io/en/add-specifiers/specifiers.html
Note: this PR is going into `new-docs`
=> New docs: add specifier documentation

.buildkite/integration_tests.sh
Note this PR is going into `new-docs`
=> New docs: Only run doc tests on 3.6 or above

docs/source/conf.py
This will
* Generate slightly prettier TOCs/lists [see](https://recommonmark.readthedocs.io/en/latest/auto_structify.html#auto-toc-tree)
* Will allow us to use RST warn/note boxes inside markdown [see](https://recommonmark.readthedocs.io/en/latest/auto_structify.html#embed-restructuredtext)
=> New docs: Enable Autostructify for recommonmark

.readthedocs.yml, docs/Makefile
Warnings usually indicate that links are broken or we forgot to include documentation files
=> New docs: fail on warning

.readthedocs.yml, docs/environment.yml, docs/requirements.txt, docs/source/conf.py
Get rid of "Pygments lexer name 'ipython3' is not known" error
=> New docs: fix RTD build

docs/requirements.txt, docs/source/conf.py
Even with redirects people may still hit a 404. Making it friendly.
=> New docs: add a not found page

pybatfish/client/asserts.py, tests/client/test_assert.py
`remote_nodes` support for assertions was busted because questions use camelCase for parameters. 
Bug report came in via slack in this thread: https://batfish-org.slack.com/archives/C8XKQNHAQ/p1590428151228800
This fixes it. 
We should probably integration test more of the asserts.
=> Fix remote_nodes parameter handling for session asserts

tests/integration/test_diagnostics.py
AWS requests can fail during test assertions (i.e. when we're checking the result of uploading during integration testing), so use the same session for test assertions that we use for diagnostic upload which retries on transient AWS request errors.
=> Fix diagnostics upload test

setup.py
https://ipython.readthedocs.io/en/stable/whatsnew/version7.html#stop-support-for-python-3-5-adopt-nep-29
=> Pin ipython; it has dropped support for py3.5

pybatfish/client/_diagnostics.py, pybatfish/client/resthelper.py, pybatfish/client/restv2helper.py, tests/client/test_diagnostics.py, tests/client/test_resthelper.py, tests/client/test_restv2helper.py
Old adapters were configured incorrectly (ignored in favor of default longer-prefix adapters `https://` and `http://` [see here for more details](https://requests-mock.readthedocs.io/en/latest/adapter.html)).
This PR adds retry for failed POST calls as well as overriding the default http and https adapters, so we actually retry.
=> Fix requests adapters

tests/integration/test_network_funcs.py
Fix auto-complete tests to only use new session method for the new test.
=> Auto-complete: fix integration tests

pybatfish/client/resthelper.py, pybatfish/client/restv2helper.py, tests/client/test_resthelper.py, tests/client/test_restv2helper.py
Explicitly set `total` retries so it doesn't default to a large value (10 for urllib3 `1.25.8`). This allows misc errors (e.g. SSLErrors/bad certificate) to timeout quickly when establishing new connections to the backend.
=> Coordinator Errors: limit retries for other issues

tests/common_util.py, tests/integration/test_notebook.py
Add ability to skip notebook tests for older versions of Batfish or Pybatfish.
Useful for new notebooks exercising new functionality not in older versions.
=> Notebook Testing: add ability to skip tests for old versions

tests/integration/test_notebook.py
Make sure entries in the notebook version testing matrix correspond to a notebook file (e.g. flag typos in notebook names in the dict).
=> Notebook tests: check notebook version testing matrix validity

.buildkite/integration_tests.sh, .buildkite/unit_tests.sh
Over the weekend, codecov was down and all our builds failed. Let this step
soft-fail.
```
+ bash /dev/fd/63 -t 59baa5fe-139e-4aef-80a7-b40bfaa3fc67
++ curl -s https://codecov.io/bash
/dev/fd/63: line 2: syntax error near unexpected token `<'
/dev/fd/63: line 2: `<html><head>'
```
=> CI: don't fail build if codecov is down

setup.py
Classifiers were already stale, but now more-so after removing 3.5 support.
=> Setup: update programming language classifiers

tests/integration/test_notebook.py
And also mark all notebooks as breaking since yesterday. Our drop of py3.5 (#691) is effectively breaking.
=> Allow a global skip of notebook tests

tests/integration/test_diagnostics.py
Fix diagnostics retry in integration tests, e.g. failure [here](https://buildkite.com/batfish/pybatfish-pre-commit/builds/17462#4befaf69-1be7-4b86-b684-60e3fba2dfbe) occurred because an adapter with a longer prefix-match was found (default `https://` vs custom `http`).
Similar to the change in https://github.com/batfish/pybatfish/pull/655.
=> Tests: fix diagnostic retry

docs/networks/example-bgp/configs/as2core2.cfg, docs/networks/example/configs/as2core2.cfg, docs/networks/failure-analysis/configs/sanfrancisco.cfg, docs/networks/forwarding-change-validation/base/configs/core2.cfg, docs/networks/forwarding-change-validation/change1-fixed/configs/core2.cfg, docs/networks/forwarding-change-validation/change1/configs/core2.cfg, docs/networks/forwarding-change-validation/change2-fixed/configs/core2.cfg, docs/networks/forwarding-change-validation/change2/configs/core2.cfg, docs/source/notebooks/configProperties.ipynb, jupyter_notebooks/Getting started with Batfish.ipynb, jupyter_notebooks/networks/example-bgp/configs/as2core2.cfg, jupyter_notebooks/networks/example/configs/as2core2.cfg, jupyter_notebooks/networks/failure-analysis/configs/sanfrancisco.cfg, jupyter_notebooks/networks/forwarding-change-validation/base/configs/core2.cfg, jupyter_notebooks/networks/forwarding-change-validation/change1-fixed/configs/core2.cfg, jupyter_notebooks/networks/forwarding-change-validation/change1/configs/core2.cfg, jupyter_notebooks/networks/forwarding-change-validation/change2-fixed/configs/core2.cfg, jupyter_notebooks/networks/forwarding-change-validation/change2/configs/core2.cfg
Future work in batfish will make these undefined references impact routing. Before that
happens, preserve undefined references AND routing behavior by adding a unused, undefined
reference.
=> examples: move undefined reference

docs/requirements.txt
The issue that caused the pin (https://github.com/spatialaudio/nbsphinx/issues/549) in #722 is resolved. 
Pinning was causing doc building to fail (#726).
=> Unpin docutils from docs/requirements.txt

fix_format.sh
Fix CI failures like this:
https://buildkite.com/batfish/pybatfish-pre-commit/builds/21575#b76894ea-1cae-4eb7-ac7a-1565d916fe4c/101-143
I'm just following the recommendation from the error message. Maybe there's a better way (or place?) to do this.
More info: https://click.palletsprojects.com/en/8.0.x/unicode-support/
=> CI: black requires we use C.UTF-8 encoding

docs/requirements.txt
The old, pinned version has become incompatible with latest Jinja.
=> Upgrade sphinx in docs/requirements.txt

setup.py
Bump `netconan` version to `0.12` which, among other things, turns on the new `preserve-host-bits` feature.
----
This new feature preserves the last octet by default. See [the `preserve-host-bits` PR for more details](https://github.com/intentionet/netconan/pull/150), but before this feature, a link 10.0.0.1/30 and 10.0.0.2/30 will be broken 3/4 of the time because one of the IPs may get anonymized to 10.0.0.0 (the network address) or 10.0.0.3 (the broadcast address).
Similarly, with no order-preservation guarantees, things like IP ranges or NAT pools might have been anonymized in a way that the anonymized `end` address comes before the anonymized `start` address.
=> Netconan: bump required version

docs/source/formats.md
Sometimes Cumulus files don't have a newline in the end, which mixes lines from two files.
=> Docs: Add newlines in Cumulus packaging

docs/source/notebooks/interacting.ipynb
The primary change, besides minor cleanup, is to include a simple example of Pandas filtering on initIssues, to show a primary usage modality and to help users that get too many initIssues and then don't know how to ignore ones that don't matter as much.
=> Update getting started instructions

tests/integration/test_network_funcs.py
- auto_complete with max_suggestions broken until batfish/pybatfish#851
- only run auto_complete tests with max_suggestions if pybatfish new enough
=> Fix autocomplete integration tests

.buildkite/build_docs.sh, .buildkite/integration_tests.sh, .buildkite/unit_tests.sh, .github/workflows/precommit.yml, .github/workflows/reusable-precommit.yml
Port buildkite pipeline to GitHub Actions with minor changes:
* Use newer python version where possible
* Use Bazel instead of Maven
* Remove some unnecessary step dependencies
=> CI: Precommit GitHub Actions workflow

pybatfish/client/asserts.py, pybatfish/client/session.py, tests/client/test_assert.py
- Fixes batfish/pybatfish#863
- Default to False
- When True, will not flag router-ids duplicated only on the same node
=> Add ignore_same_node option to assert_no_duplicate_router_ids

docs/source/notebooks/routingProtocols.ipynb, jupyter_notebooks/Analyzing Routing Policies.ipynb
This PR updates the values used in the "Analyzing Routing Policies" notebook to align them with the values produced by an updated version of SearchRoutePolicies from [this PR](https://github.com/batfish/batfish/pull/8642).
Should be merged after [https://github.com/batfish/batfish/pull/8642](https://github.com/batfish/batfish/pull/8642).
=> Update values in Routing Policies notebook.

pybatfish/client/session.py
Stop advertising this functionality.
commit-id:dbbb939f
=> Session: flip enable_diagnostics to False

setup.py
=> pybatfish: explicit urllib3 lower bound

.pre-commit-config.yaml, setup.py
> Black now has an official pre-commit mirror. Swapping
> https://github.com/psf/black to https://github.com/psf/black-pre-commit-mirror
> in your .pre-commit-config.yaml will make Black about 2x faster (#3828)
=> black: upgrade to latest, switch to official mirror

.github/workflows/reusable-precommit.yml, pybatfish/client/asserts.py, pybatfish/client/restv2helper.py, pybatfish/question/question.py, setup.py, tests/question/test_question_additional.py
Fix https://github.com/python/cpython/issues/100458
Fix a pandas incompatibility
=> CI: try with 3.11 and 3.12

tests/integration/test_network_funcs.py, tests/integration/test_snapshot_funcs.py
This is required since we moved to session-level functions after deleting the old
default session.
=> test_[network,snapshot]_funcs: adjust requires_bf

pybatfish/client/session.py, tests/client/test_session.py
Add `port` param, prefer it over `port_v2`, but keep the latter for backwards compatibility
Fixes #917
=> Add `port` as an argument to session

setup.py
No longer used. Last feature that used it was diagnostics, and that was removed in #909
=> Remove netconan as a dependency

docs/source/formats.md
I have been looking at these more and noticed some stuff is missing. I went ahead and added what I could verify.
Methodology: I used https://github.com/ratulm/bf-aws-snapshot/blob/master/awshelper.py as a baseline to find what is possibly undocumented. I then looked for correlating files in https://github.com/batfish/batfish/tree/fa13c21a0e8efd5b76c0eb50978df0f7cc6f34e5/projects/batfish/src/main/java/org/batfish/representation/aws and checked their classes to see if they looked the same. Some things like `describe_classic_link_instances` do not seem to be modeled even though the helper script pulls them.
The lists have also been sorted alphabetically.
=> Updating formats.md with more AWS JSON configuration files

.github/workflows/reusable-precommit.yml, .readthedocs.yml
Sometime in October 2024, RTD made a breaking change and broke our build.
Last working: https://app.readthedocs.org/projects/pybatfish/builds/25850120/
First failing: https://app.readthedocs.org/projects/pybatfish/builds/25876957/
Many major version changes, etc.
It seems that the issue is related to the htmlzip build reusing some
intermediate state from the first build. If I manually only build one
OR the other, it works fine.
For now, disable the htmlzip build (html is required) to unblock.
=> Add readthedocs to precommit, fix build

pybatfish/client/session.py, tests/client/test_session.py
Removes this warning from 3.13 while keeping pybatfish working from 3.9 to 3.13. This is mildly annoying because 3.10 is where the entry_points API stabilized.
> pybatfish/client/session.py:36: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
=> pkg_resources to importlib.metadata conversion

.github/workflows/reusable-precommit.yml, pyproject.toml
Adds Python 3.14 support to CI test matrix and package classifiers.
=> Add Python 3.14 to test matrix and classifiers
